<?php /** @var $this \Rubic\SimpleCheckout\Block\Customizer */ ?>
<style type="text/css" media="screen and (min-width: 768px)">
    #checkout {
        background-color: <?php echo $this->getCheckoutBackgroundColor(); ?>;
        border: solid 1px <?php echo $this->getCheckoutBorderColor(); ?>;
    }
    body {
        background-color: <?php echo $this->getBodyBackgroundColor(); ?>;
    }
</style>