<?php
/**
 * Copyright © 2018 Rubic. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php /** @var $this \Rubic\CleanCheckout\Block\Customizer */ ?>
<style type="text/css" media="screen and (min-width: 768px)">
    #checkout {
        background-color: <?php echo $this->getCheckoutBackgroundColor(); ?>;
        border: solid 1px <?php echo $this->getCheckoutBorderColor(); ?>;
    }
    .opc-wrapper {
        border-right: solid 1px <?php echo $this->getCheckoutBorderColor(); ?>;
    }
    body {
        background-color: <?php echo $this->getBodyBackgroundColor(); ?>;
    }
</style>

<?php $customCss = $this->getCustomCss(); ?>
<?php if ($customCss): ?>
<style type="text/css">
    <?php echo $customCss; ?>
</style>
<?php endif; ?>